# this is the actual ingrdients for the recipes
p "seeding foods"

# creating each of the recipes

FOODS = [
  {  name: "1/4 cup Almond Meal Flour",
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1 tsp Sucralose Based Sweetener (Sugar Substitute)',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1/4 tsp Baking Powder (Straight Phosphate, Double Acting)',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1/8 tsp Salt',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1/2 tsp Cinnamon',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1 large Egg (Whole)',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1 tsp Canola Vegetable Oil',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1/4 cup Frozen Blackberries',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1 cup Coconut Milk Unsweetened',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1 oz Vanilla Whey Protein',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1/16 cup Organic 100% Whole Ground Golden Flaxseed Meal',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1/4 tsp Cinnamon',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1/16 tsp Allspice Ground',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1/2 tsp Vanilla Extract',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1/2 tsp Salt',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },   {  name: '1/4 tsp Red or Cayenne Pepper',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1 tbsp Canola Vegetable Oil',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '4 large Eggs (Whole)',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '3 tbsps Sweet Red Peppers',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '2 tbsps chopped Scallions or Spring Onions',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1 Jalapeno Pepper',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '2 tortillas Low Carb Tortillas',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/8 tsp Tabasco Sauce',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '2 oz Salsa',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '12 oz Zucchini',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '3/4 tsp Salt',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '5 medium Carrots',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1 small Onion',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/2 tsp Black Pepper',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/2 cup Canola Vegetable Oil',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1 1/2 servings Atkins Cuisine Bread',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/4 cup shredded Cheddar Cheese',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/3 cup chopped Onions',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1 1/2 servings Atkins Cuisine 1/4 cup Shiitake Mushrooms',
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '2 large Eggs (Whole)',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/2 clove Garlic',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/2 tbsp Tamari Soybean Sauce',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/4 tbsp Sodium and Sugar Free Rice Vinegar',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/4 tsp Sesame Oil',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/8 tsp Sucralose Based Sweetener (Sugar Substitute)',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/8 tsp Curry Powder',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/16 tsp Ginger',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '4 1/4 oz Beef Top Sirloin (Trimmed to 1/8" Fat, Choice Grade)',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '3/4 cup Spring Mix Salad',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/2 tbsp Canola Vegetable Oil',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/4 large (2-1/4 per lb, approx 3-3/4" long, 3" dia) Sweet Red Peppers',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '2 oz Waterchestnuts',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1 large Scallions or Spring Onion',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '10 oz Arugula (Rocket)',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/2 cup crumbled Gorgonzola Cheese',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '2 servings Maple-Dijon Vinaigrette',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1 medium (approx 2-1/2 per lb) Pears',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '40 nuts Hazelnuts or Filberts',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '5 1/3 tbsps Tamari Gluten Free Soy Sauce',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '2 2/3 fl ozs Rice Wine',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1 tbsp Toasted Sesame Oil',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1 tbsp Ginger',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '3 tsps Garlic',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '2 tsps Sucralose Based Sweetener (Sugar Substitute)',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '32 oz boneless Tuna',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '3 large Scallions or Spring Onions',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1 large (2.25 per pound, approx 3-3/4" long, 3" dia) Red Sweet Pepper',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '3/4 lb Eggplant',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '3 cups chopped Scallions or Spring Onions',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '2 cups Mushroom Pieces and Stems',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '4 tbsps Tamari Soybean Sauce',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '3 tsps Ginger',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1 clove Garlic',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1 pepper Serrano Pepper',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1 cup chopped or sliced Red Tomato',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '6 oz Firm Silken Tofu',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1 carrot (7-1/2") Carrots',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/2 oz Cilantro (Coriander)',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '2 cups shredded Chinese Cabbage (Bok-Choy, Pak-Choi)',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '6 cups Chicken Broth, Bouillon or Consomme',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1 tbsp Extra Virgin Olive Oil',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '3 14.5 oz cans Chicken Broth, Bouillon or Consomme',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '2 lbs Asparagus',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '3 stalk medium (7-1/2" - 8" long) Celery',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/4 tsp Salt',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/4 tsp Black Pepper',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '1/2 tbsp leaf Tarragon',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    },
    {  name: '3/4 cup Heavy Cream',
      vegan: true,
      paleo: false,
      basic: true,
      atkins: true,
      ectomorphs: true,
      mesomorphs: true,
      endomorphs: true,
      protein: 0,
      carbohydrate: 0,
      calories: 0,
      fat: 0,
    }
]

FOODS.each do |food|
  Food.find_or_create_by!(
    name: food[:name],
    vegan: food[:vegan],
    paleo: food[:paleo],
    basic: food[:basic],
    atkins: food[:atkins],
    ectomorphs: food[:ectomorphs],
    mesomorphs: food[:mesomorphs],
    endomorphs: food[:endomorphs],
    protein: food[:protein],
    carbohydrate: food[:carbohydrate],
    calories: food[:calories],
    fat: food[:fat]
  )
end
