# this is the actual ingrdients for the recipes
p "seeding foods"

# creating each of the recipes

FOODS = [
  {  name: "1/4 cup Almond Meal Flour",
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1 tsp Sucralose Based Sweetener (Sugar Substitute)',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1/4 tsp Baking Powder (Straight Phosphate, Double Acting)',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1/8 tsp Salt',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1/2 tsp Cinnamon',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1 large Egg (Whole)',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  },
  {  name: '1 tsp Canola Vegetable Oil',
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 0,
    carbohydrate: 0,
    calories: 0,
    fat: 0,
  }
]

FOODS.each do |food|
  Food.find_or_create_by!(
    name: food[:name],
    vegan: food[:vegan],
    paleo: food[:paleo],
    basic: food[:basic],
    atkins: food[:atkins],
    ectomorphs: food[:ectomorphs],
    mesomorphs: food[:mesomorphs],
    endomorphs: food[:endomorphs],
    protein: food[:protein],
    carbohydrate: food[:carbohydrate],
    calories: food[:calories],
    fat: food[:fat]
  )
end
