p "seeding ingredients"
# create an association between recipe and food,
# each is a new instance
#
INGREDIENTS = [
  {  recipe_id: 1,
  },
  {  recipe_id: 1,
    food_id: 2,
  },
  {  recipe_id: 1,
    food_id: 3,
  },
  {  recipe_id: 1,
    food_id: 4,
  },
  {  recipe_id: 1,
    food_id: 5,
  },
  {  recipe_id: 1,
    food_id: 6,
  },
  {  recipe_id: 1,
    food_id: 7,
  },
  {  recipe_id: 2,
    food_id: 8,
  },
  {  recipe_id: 2,
    food_id: 9,
  },
  {  recipe_id: 2,
    food_id: 10,
  },
  {  recipe_id: 2,
    food_id: 11,
  },
  {  recipe_id: 2,
    food_id: 12,
  },
  {  recipe_id: 2,
    food_id: 13,
  },
  {  recipe_id: 2,
    food_id: 14,
  },
  {  recipe_id: 3,
    food_id: 15,
  },
  {  recipe_id: 3,
    food_id: 16,
  },
  {  recipe_id: 3,
    food_id: 17,
  },
  {  recipe_id: 3,
    food_id: 18,
  },
  {  recipe_id: 3,
    food_id: 19,
  },
  {  recipe_id: 3,
    food_id: 20,
  },
  {  recipe_id: 3,
    food_id: 21,
  },
  {  recipe_id: 3,
    food_id: 22,
  },
  {  recipe_id: 3,
    food_id: 23,
  },
  {  recipe_id: 3,
    food_id: 24,
  },
  {  recipe_id: 4,
    food_id: 25,
  },
  {  recipe_id: 4,
    food_id: 26,
  },
  {  recipe_id: 4,
    food_id: 27,
  },
  {  recipe_id: 4,
    food_id: 28,
  },
  {  recipe_id: 4,
    food_id: 18,
  },
  {  recipe_id: 4,
    food_id: 29,
  },
  {  recipe_id: 4,
    food_id: 30,
  },
  {  recipe_id: 4,
    food_id: 31,
  },
  {  recipe_id: 5,
    food_id: 32,
  },
  {  recipe_id: 5,
    food_id: 33,
  },
  {  recipe_id: 5,
    food_id: 7,
  },
  {  recipe_id: 5,
    food_id: 34,
  },
  {  recipe_id: 5,
    food_id: 35,
  },
  {  recipe_id: 6,
    food_id: 36,
  },
  {  recipe_id: 6,
    food_id: 37,
  },
  {  recipe_id: 6,
    food_id: 38,
  },
  {  recipe_id: 6,
    food_id: 39,
  },
  {  recipe_id: 6,
    food_id: 40,
  },
  {  recipe_id: 6,
    food_id: 41,
  },
  {  recipe_id: 6,
    food_id: 42,
  },
  {  recipe_id: 6,
    food_id: 43,
  },
  {  recipe_id: 6,
    food_id: 44,
  },
  {  recipe_id: 6,
    food_id: 45,
  },
  {  recipe_id: 6,
    food_id: 46,
  },
  {  recipe_id: 6,
    food_id: 47,
  },
  {  recipe_id: 6,
    food_id: 48,
  },
  {  recipe_id: 7,
    food_id: 49,
  },
  {  recipe_id: 7,
    food_id: 50,
  },
  {  recipe_id: 7,
    food_id: 51,
  },
  {  recipe_id: 7,
    food_id: 52,
  },
  {  recipe_id: 7,
    food_id: 53,
  },
  {  recipe_id: 8,
    food_id: 54,
  },
  {  recipe_id: 8,
    food_id: 55,
  },
  {  recipe_id: 8,
    food_id: 56,
  },
  {  recipe_id: 8,
    food_id: 57,
  },
  {  recipe_id: 8,
    food_id: 58,
  },
  {  recipe_id: 8,
    food_id: 59,
  },
  {  recipe_id: 8,
    food_id: 60,
  },
  {  recipe_id: 8,
    food_id: 61,
  },
  {  recipe_id: 8,
    food_id: 62,
  },
  {  recipe_id: 8,
    food_id: 63,
  },
  {  recipe_id: 9,
    food_id: 64,
  },
  {  recipe_id: 9,
    food_id: 65,
  },
  {  recipe_id: 9,
    food_id: 66,
  },
  {  recipe_id: 9,
    food_id: 67,
  },
  {  recipe_id: 9,
    food_id: 68,
  },
  {  recipe_id: 9,
    food_id: 69,
  },
  {  recipe_id: 9,
    food_id: 70,
  },
  {  recipe_id: 9,
    food_id: 71,
  },
  {  recipe_id: 9,
    food_id: 72,
  },
  {  recipe_id: 9,
    food_id: 73,
  },
  {  recipe_id: 9,
    food_id: 74,
  },
  {  recipe_id: 9,
    food_id: 75,
  },
  {  recipe_id: 10,
    food_id: 76,
  },
  {  recipe_id: 10,
    food_id: 77,
  },
  {  recipe_id: 10,
    food_id: 78,
  },
  {  recipe_id: 10,
    food_id: 79,
  },
  {  recipe_id: 10,
    food_id: 80,
  },
  {  recipe_id: 10,
    food_id: 81,
  },
  {  recipe_id: 10,
    food_id: 82,
  },
  {  recipe_id: 10,
    food_id: 83,
  },
  {  recipe_id: 10,
    food_id: 28,
  }
]
  INGREDIENTS.each do |ingredient|
    Ingredient.find_or_create_by!(
      recipe_id: ingredient[:recipe_id],
      food_id: ingredient[:food_id]
    )
  end
