# this is the actual ingrdients for the recipes
p "seeding nutrition table"

# creating each of the recipes

NUTRITION = [
  {  name: "nuts",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: false,
    endomorphs: false,
    good_for_you: true,
  },
  {  name: "whey powder",
    vegan: false,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: false,
    endomorphs: false,
    good_for_you: true,
  },
  {  name: "bagels",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: false,
    endomorphs: false,
    good_for_you: true,
  },
  {  name: "dried fruits",
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: false,
    endomorphs: false,
    good_for_you: true,
  },
  {  name: "fish",
    vegan: false,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    good_for_you: true,
  },
  {  name: "eggs",
    vegan: false,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: true,
  },
  {  name: "oats",
    vegan: false,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: false,
    endomorphs: false,
    good_for_you: true,
  },
  {  name: "asparagus",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: true,
  },
  {  name: "artichokes",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: true,
  },
  {  name: "spinach",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: true,
  },
  {  name: "bananas",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: true,
  },
  {  name: "tomatoes",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: true,
    endomorphs: true,
    good_for_you: true,
  },
  {  name: "almonds",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: true,
  },
  {  name: "chicken",
    vegan: false,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    good_for_you: true,
  },
  {  name: "beans",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: true,
  },
  {  name: "beef",
    vegan: false,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: true,
  },
  {  name: "grains",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: true,
  },
  {  name: "zucchini",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: true,
  },
  {  name: "pepper",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: true,
  },
  {  name: "squash",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: true,
  },
  {  name: "onions",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: true,
  },
  {  name: "lettuce",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: true,
  },
  {  name: "green beans",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: true,
  },
  {  name: "sugars",
    vegan: true,
    paleo: false,
    basic: true,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: false,
  },
  {  name: "lard",
    vegan: false,
    paleo: false,
    basic: true,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: false,
  },
  {  name: "excess cheese",
    vegan: false,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: false,
  },
  {  name: "butter",
    vegan: false,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: false,
  },
  {  name: "pastries",
    vegan: false,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: false,
  },
  {  name: "coffee drinks",
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: false,
  },
  {  name: "fried foods",
    vegan: true,
    paleo: false,
    basic: true,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: false,
  },
  {  name: "liquor",
    vegan: false,
    paleo: false,
    basic: true,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: false,
  },
  {  name: "gravy",
    vegan: false,
    paleo: false,
    basic: true,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: false,
  },
  {  name: "cold meats",
    vegan: false,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: false,
  },
  {  name: "beef",
    vegan: false,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: false,
    good_for_you: false,
  },
  {  name: "large amount of beef",
    vegan: false,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: false,
  },
  {  name: "large amount of chicken",
    vegan: false,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: false,
  },
  {  name: "bananas",
    vegan: true,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: false,
  },
  {  name: "pork",
    vegan: false,
    paleo: true,
    basic: true,
    atkins: false,
    ectomorphs: false,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: false,
  },
  {  name: "cream",
    vegan: false,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: false,
  },
  {  name: "cheese",
    vegan: false,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: false,
  },
  {  name: "pasta",
    vegan: false,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: false,
  },
  {  name: "rice",
    vegan: true,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: false,
  },
  {  name: "sausage",
    vegan: false,
    paleo: false,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: false,
  },
  {  name: "colas",
    vegan: false,
    paleo: true,
    basic: true,
    atkins: true,
    ectomorphs: false,
    mesomorphs: false,
    endomorphs: true,
    good_for_you: false,
  }
]

NUTRITION.each do |nutrition|
  Nutrition.find_or_create_by!(
    name: nutrition[:name],
    vegan: nutrition[:vegan],
    paleo: nutrition[:paleo],
    basic: nutrition[:basic],
    atkins: nutrition[:atkins],
    ectomorphs: nutrition[:ectomorphs],
    mesomorphs: nutrition[:mesomorphs],
    endomorphs: nutrition[:endomorphs],
    good_for_you: nutrition[:good_for_you]
  )
end
