p "seeding recipes"

# creating each of the recipes

RECIPES = [
  {  name: "Almond Muffin",
    instructions: "1.	Place all dry ingredients in a coffee mug.  Stir to combine. 2.	Add the egg and oil.  Stir until thoroughly combined.  3.	Microwave for 1 minute. Use a knife if necessary to help remove the muffin from the cup, slice, butter, eat.12.3g",
    category: "breakfast",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 12.3,
    carbohydrate: 4.5,
    calories: 279,
    fat: 23.4,
  },
  {  name: "Blackberry Smoothie",
    instructions: "For this recipe unsweetened coconut, almond or soy milk may be used.  Combine the frozen balckberries, milk of choice, protein powder, flax meal (1/16 cup = 1 Tbsp), vanilla and spices in a blender.  Blend until smooth.",
    category: "breakfast",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 21.8,
    carbohydrate: 6.7,
    calories: 221,
    fat: 9.8,
  },
  {  name: "Breakfast Burrito",
    instructions: "	1.	Whisk eggs, salt and cayenne together in a bowl.
	2.	In a medium skillet over medium heat, toast tortillas 1 minute per side until brown in spots; set aside and cover with foil to keep warm.
	3.	In the same skillet add oil, red pepper, scallion whites and jalapeno.  Cook until vegetables are softened, about 3 minutes.
	4.	Add eggs and continue to cook, stirring, until eggs are set, about 2 minutes.
	5.	Place tortillas on plates. Divide eggs between tortillas, season with hot sauce and gently roll up.
	6.	Serve with salsa and scallion greens.",
    category: "breakfast",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 17.8,
    carbohydrate: 7.9,
    calories: 281,
    fat: 19.2,
  },
  {  name: "Carrot-Zucchini Latkes",
    instructions: "Use the Atkins recipe to make Atkins Cuisine Bread for this recipe.
	1.	Heat oven to 300°F. Set a rack on a baking sheet.
	2.	Grate zucchini in a food processor fitted with shredding blade or with a box grater, using the side with the largest holes. Transfer to a bowl; sprinkle with 1/4 teaspoon of the salt and toss. Let stand while you prepare the remaining ingredients.
	3.	Grate carrots and white onion in food processor or with the grater. Transfer to a large bowl. 
	4.	Put bread on a baking sheet and toast in the oven until dried out, 10 to 14 minutes. Leave oven on. Transfer bread to food processor and pulverize to make crumbs. Add crumbs, eggs, remaining 1/2 teaspoon salt and pepper to carrots. Transfer zucchini to a clean dish towel and squeeze out excess liquid. Add zucchini to carrot mixture and stir well to combine. 
	5.	Heat 1/2 cup of canola oil (may need to add more during cooking) in a large skillet over medium heat until very hot. Drop batter by heaping tablespoons into oil and flatten to 3-inch pancakes; do not crowd pan. Cook until golden brown, 3 to 4 minutes per side. Transfer to paper towels to drain; then set on prepared baking sheet and keep latkes warm in oven. Repeat, adding more oil if necessary, making a total of 24 latkes. Serve with sour cream or a squeeze of lemon (optional).",
    category: "breakfast",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 5,
    carbohydrate: 5,
    calories: 197,
    fat: 17.1,
  },
  {  name: "Cheddar Omelet with Sautéed Onions and Shiitake Mushrooms",
    instructions: "	1.	Heat oil in a nonstick skillet or omelet pan over medium-high heat. Add onions and mushrooms. Sauté for about 5 minutes until onions are translucent and mushrooms are soft. Remove from pan and set aside. 
	2.	Add eggs to the skillet. Cook 3 minutes, lifting the edges of the egg to allow uncooked eggs to flow over and cook. Flip over and cook another 2 minutes. 
	3.	Add onions and mushrooms to half of omelet and top with cheese. Fold other half over and cook 1 2 minutes more to melt cheese. Serve immediately.",
    category: "breakfast",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 21.5,
    carbohydrate: 7.6,
    calories: 339,
    fat: 23.9,
  },
  {  name: "Asian Beef Salad Single Serving",
    instructions: "	Note: Because only half of the marinade is used in this recipe for the salad dressing and the rest is used as a marinade and discarded, please double the first six ingredients. (The nutritionals shown are correct.) For added flavor, use dark (toasted) sesame oil instead of regular sesame oil.
	1.	Mix green onions, garlic, soy sauce, rice wine vinegar, sesame oil and sugar substitute in a small bowl. Pour half into a resealable plastic bag; add steak and marinate overnight in the refrigerator.
	2.	To remaining soy sauce mixture, add curry powder and ginger.Heat canola oil in a large skillet over high heat until very hot.
	3.	Drain beef and discard marinade; quickly stir-fry beef 2 to 3 minutes in hot oil for medium doneness. Transfer to a large mixing bowl. Add salad greens, bell pepper, water chestnuts and reserved soy dressing. Toss to coat and serve immediately.",
    category: "lunch",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 29.5,
    carbohydrate: 10.4,
    calories: 295,
    fat: 13.3,
  },
  {  name: "Arugula, Pear and Hazelnut Salad",
    instructions: "Use the Atkins recipe to make Maple-Dijon Vinaigrette for this recipe.  You will need 4 Tbsp.  This salad is delicious served with salmon.
	1.	Toast hazelnuts in a dry skillet for about 15 minutes or toast on a sheet pan in an oven at 350°F (stir 2-3 times for both methods); allow to cool and gently rub off outer skin, coarsely chop, and set aside.  
	2.	Make the Maple-Dijon Vinaigrette and toss 4 tablespoons with the arugula and Gorgonzola cheese.  Transfer to serving plates.  
	3.	Arrange the pear slices in a fan on top and sprinkle with hazelnuts.",
    category: "lunch",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 7.1,
    carbohydrate: 8,
    calories: 244,
    fat: 20,
  },
  {  name: "Asian Tuna Kebabs",
    instructions: "You'll need 8 bamboo skewers, which should be soaked in water for 15 minutes before cooking. Or use metal skewers. Chinese eggplants are thinner and less bitter than Italian ones and can be found in Asian markets or well-stocked produce sections of most supermarkets.
	1.	Heat grill to high.
	2.	Combine soy sauce, rice wine, sesame oil, ginger, garlic and sugar substitute in a large bowl.
	3.	Add tuna, scallions and red pepper and toss to coat. Marinate for 15 minutes in the refrigerator. Remove tuna, scallions and red pepper from marinade and set aside.
	4.	Toss eggplant in marinade and let sit for 3 minutes. Remove eggplant and set aside with other ingredients. Discard marinade.
	5.	Thread skewers, alternating 3 pieces of tuna, 2 pieces of scallions, 2 pieces of red pepper and 3 pieces of eggplant on each. Eggplant should be skewered through both skin sides of the rounds.
	6.	Grill for 3 4 minutes per side tuna will be rare in the center. ",
    category: "lunch",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 28,
    carbohydrate: 3.9,
    calories: 221,
    fat: 7.5,
  },
  {  name: "Asian Vegetable Bowl",
    instructions: "To make this soup suitable for earlier phases, simply omit the carrot.   Also vegetable broth may be substituted for the chicken broth to make it appropriate for Vegetarians and Vegans.
	1.	In a large saucepan, bring broth and tamari to a boil.
	2.	Reduce heat; add bok choy, mushrooms, ginger, garlic (minced) and chili. Simmer for 5 minutes, until bok choy is tender but still crisp and mushrooms are softened.
	3.	Add tomatoes, green onions, tofu and carrot. Heat through for 1 minute.
	4.	Stir in cilantro just before serving.",
    category: "lunch",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 28,
    carbohydrate: 3.9,
    calories: 221,
    fat: 7.5,
  },
  {  name: "Asparagus Tarragon Cream Soup",
    instructions: "	1.	Heat oil in a large pot over medium-high heat. Add white onion and cook 5 minutes, until softened but not browned.
	2.	Add broth, asparagus, celery, salt, pepper and half of the tarragon to the pot. Bring to a boil.
	3.	Lower heat, cover and simmer 20 minutes, until asparagus is very tender.
	4.	In a blender, puré soup in batches until smooth.  Return to pot.  Add cream and remaining tarragon and heat soup through over medium heat.   Season with salt and freshly ground black pepper.",
    category: "lunch",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 3.9,
    carbohydrate: 4,
    calories: 128,
    fat: 10.5,
  },
  {  name: "Baked Catfish with Broccoli and Herb-Butter Blend",
    instructions: "Cooking fish in an aluminum-foil packet makes for easy cleanup and works especially well for single portions. Add a vegetable and you have a complete quick meal.  Use any compound butter or use 1 tablespoon of the Atkins recipe:  Herb-Butter Blend.
	1.	Preheat oven to 350°F.
	2.	Place the catfish on a 12-inch square piece of foil. Sprinkle fish with salt and freshly ground pepper to taste. Arrange broccoli florets around fish.
	3.	Fold up the sides of the foil and crimp tightly to form a sealed packet.
	4.	Bake for 10 15 minutes until fish is flaky and broccoli is tender.
	5.	Transfer to a dish, open foil and top with a tablespoon of Herb-Butter Blend.",
    category: "dinner",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 28.7,
    carbohydrate: 3.7,
    calories: 362,
    fat: 25.9,
  },
  {  name: "Baked Chicken with Artichokes",
    instructions: "Use the Atkins recipe to make All Purpose Low-Carb Baking Mix for this recipe.  Dredging chicken in flour before sautéing seals in the juices and give it a nice color. 
	1.	Preheat oven to 350°F. Place 1/4 cup baking mix, salt and pepper in a shallow plate and mix well. Dredge chicken in the mixture, turning to coat evenly and then tapping to remove any excess.
	2.	In large skillet, heat oil over medium-high heat. Cook chicken until lightly browned, turning once, about 4 minutes. Transfer to baking dish.
	3.	Add onion to skillet and sauté until softened, about 2 minutes. Add mushrooms and sauté until lightly golden, about 3 more minutes. Add garlic and sauté until aroma is released, about 30 seconds. Stir in wine, artichokes, rosemary and red pepper flakes and bring to a simmer.
	4.	Pour artichoke mixture over chicken in the baking dish, cover and bake 40 minutes, until chicken is tender and cooked through. Season with additional salt and pepper, if desired, and stir in oregano before serving.",
    category: "dinner",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 37.5,
    carbohydrate: 8.6,
    calories: 376,
    fat: 17.8,
  },
  {  name: "Baked Fennel au Gratin",
    instructions: "Use the Atkins recipe to make All Purpose Low-Carb Baking Mix for this recipe.
	1.	Preheat oven to 375°F.
	2.	Grease a shallow 2-quart baking dish with 1 teaspoon butter and set aside.
	3.	Trim fennel leaving 1 stalks, Quarter bulbs and remove center core. Cut crosswise into 1/4 slices. Place fennel in a saucepan and cook in lightly salted water over medium heat until just tender, about 10 minutes. Drain fennel and season with salt and pepper. Transfer fennel to dish, pressing down to form an even layer. Set aside.
	4.	In a medium saucepan melt butter over medium heat. Stir in 3 Tbsp baking mix and cook 2 minutes.
	5.	Add cream and bring to a boil. Cook, whisking constantly, until slightly, about 5 minutes. Turn off heat and stir in Gruyere until melted.
	6.	Pour sauce evenly over fennel and sprinkle dish with Parmesan cheese.Cover with foil and bake 15 minutes; uncover and bake 15-20 minutes more until golden brown and bubbly.",
    category: "dinner",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 8.1,
    carbohydrate: 5,
    calories: 293,
    fat: 26.4,
  },
  {  name: "Baked Meatballs",
    instructions: "If possible, have the butcher grind together the three different meats. Be sure to wash your hands thoroughly after handling raw pork. 
	1.	Heat oven to 375°F.
	2.	In a skillet, over high heat, heat oil, cook onion 5 minutes, stirring frequently, until softened. Add garlic (minced) and cook 1 minute more.
	3.	Transfer to a bowl and mix in ground meats, cheese, eggs, salt, and pepper. Roll into golf ball-size meatballs. Place on a jelly roll pan.
	4.	Bake 20- 25 minutes, until browned and cooked through.",
    category: "dinner",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 38.6,
    carbohydrate: 1.8,
    calories: 409,
    fat: 26.7,
  },
  {  name: "Baked Salmon with Bok Choy and Mixed Greens",
    instructions: "Use the Atkins recipe for Sherry Vinaigrette for the salad.
	1.	Preheat oven to 475° F. Place olive oil and butter in a skillet large enough to hold fish in a single layer.
	2.	Place skillet with just the olive oil and butter into the oven for 3 minutes, until butter is melted.  Season fish with salt and pepper.  Place fish flesh side down in prepared skillet.  Bake 10 minutes, turning carefully once halfway through cooking time, until just cooked through.
	3.	Remove from skillet; tent with foil. Add bok choy and lemon peel to skillet.  Stir to coat with pan's oil.  Place in oven 1 minute, until leaves are wilted and stems are warmed through.
	4.	To make puree, blend peppers and salsa in a blender 30 seconds. 
	5.	Top bok choy with fish and dollop with the purée.
	6.	Toss the greens, okra, peppers and snow peas with the Sherry Vinaigrette.  Serve with the salmon and bok choy.",
    category: "dinner",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 37.5,
    carbohydrate: 15.4,
    calories: 623,
    fat: 44.1,
  },
  {  name: "Artichokes with Three Cheeses",
    instructions: "	1.	Preheat oven to 400°F.
	2.	Arrange artichoke hearts in a single layer on the bottom of an 11-by-7-inch (2-quart) baking dish. Top with garlic and broth. Drizzle with olive oil and lemon juice. Sprinkle with parsley and basil.
	3.	Cover evenly with the cheeses, ending with the Parmesan. Cover with aluminum foil, and bake until artichokes are tender and cheeses are melted, about 15 minutes.
	4.	Uncover and continue baking until cheese is lightly golden and slightly crusty, about 25 minutes more.
	5.	Remove from oven, and cool. Serve warm or at room temperature.",
    category: "snack",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 11.5,
    carbohydrate: 2.8,
    calories: 250,
    fat: 21.5,
  },
  {  name: "Apple Muffins with Cinnamon-Pecan Streusel",
    instructions: "1.	Preheat oven to 350 F.  Prepare a muffin tin with 8 cupcake papers.  
	2.	Combine 2/3 cup almond flour, chopped pecans, 2 tablespoons cinnamon, 1/8 teaspoon salt, 2 tablespoons granular sugar substitute (eryhtritol), a pinch of stevia and 2 tablespoons melted butter in a small bowl.  Mix with a fork until it begins to crumble.  Set aside while making the muffin batter.  
	3.	For the muffins:  whisk together the eggs, 1/4 cup coconut milk, 2 teaspoons vanilla, 6 tablespoons granular sugar substitute (erythritol), a pinch of stevia, and 1/2 teaspoon ground cinnamon.  Add 1 cup almond flour, 2 tablespoons coconut flour, 1/4 teaspoon salt and 1 teaspoon baking powder; mix to combine then fold in 2/3 cup finely chopped apples.  
	4.	Divide into muffin 8 wells topping each with about 2 tablespoons of the struesal.  Bake for 25 minutes, remove from oven and allow to sit for 10-20 minutes to cool before removing.  These may be eaten immediately or stored in an airtight container in the refrigerator for up to 1 week.",
    category: "snack",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 7.5,
    carbohydrate: 5.3,
    calories: 242,
    fat: 20.6,
  },
  {  name: "Atkins Garlic Toast Crisps",
    instructions: "Use the Atkins recipe to make All Purpose Low-Carb Baking Mix for this recipe.  Have these crispy crackers with olive tapenade or guacamole.
	1.	Heat oven to 350°F. Lightly coat an 8-inch by 4-inch loaf pan with olive oil spray.
	2.	Place olive oil and garlic in a small microwave-safe cup and microwave on high until garlic turns golden, about 1 minute. (Or cook in a small saucepan over medium-high heat, for 4 to 5 minutes, stirring occasionally.) Set aside.
	3.	In a large mixing bowl, combine baking mix (2 cups), baking powder and salt and blend well. Add club soda, eggs and 1 tablespoon of the garlic oil. Mix by hand or with an electric mixer until just combined.
	4.	Transfer dough to prepared pan, smooth top and bake 45 minutes, until a tester inserted into the center comes out clean.
	5.	Transfer loaf to a wire rack to cool for 20 minutes. Meanwhile, increase oven temperature to 400°F. 
	6.	When loaf has cooled, using a serrated knife, cut loaf into 20 thin slices. Place them on an ungreased baking sheet and brush with the remaining garlic oil, turning to coat both sides.
	7.	Bake until golden and crisp, about 14 minutes.",
    category: "snack",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 10,
    carbohydrate: 2.2,
    calories: 90,
    fat: 4.6,
  },
  {  name: "Atkins Cuisine Brownies",
    instructions: "Use the Atkins recipe to make All Purpose Low-Carb Baking Mix to use in this recipe.  You will need 1 1/4 cups.
	1.	Pre-heat oven to 325°F.
	2.	Place the unsweetened chocolate and butter together in a bowl and microwave on high power for approximately 2 minutes until chocolate is melted.  Whisk in heavy cream.
	3.	In a separate bowl, add the eggs and 1 cup of granular sugar substitute.  Beat together using an electric mixer until mixture is just blended.  Reduce mixer to low speed and then blend in the chocolate mixture.
	4.	With a wooden spoon, mix in the baking powder and 1 1/4 cups low-carb baking mix.
	5.	Coat 8 x 8 inch pan with non-stick vegetable oil spray and spread batter evenly into pan.
	6.	Bake at 325°F for 30-35 minutes or until done (toothpick inserted in the center comes out clean). (Do not over-bake or brownies will be dry and hard.)
	7.	Once cooled, cut into 5 rows by 5 rows to make 25 brownies.",
    category: "snack",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 6.6,
    carbohydrate: 2.7,
    calories: 119,
    fat: 9.4,
  },
  {  name: "Atkins Peanut Butter Granola Bar Parfait with Yogurt and Strawberries",
    instructions: "In a parfait glass, layer the granola bar (chopped) with the yogurt and strawberries.",
    category: "snack",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 24.1,
    carbohydrate: 12.6,
    calories: 314,
    fat: 9.5,
  },
  {  name: "Berries with Chocolate Ganache",
    instructions: "	1.	Combine fruit and place into 6 dessert bowls.
	2.	In a small saucepan over low heat, heat chocolate and cream until just melted (this can be done in a microwave for 30 seconds at a time.  Be careful not to overheat and burn the chocolate). Add vanilla and stir until smooth.
	3.	Cool slightly and drizzle sauce over fruit just before serving.",
    category: "snack",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 2.3,
    carbohydrate: 11.7,
    calories: 260,
    fat: 17.8,
  },
  {  name: "Black Olives with Cheddar",
    instructions: "	1.	Dice the cheese and place into hole in the olive.  
	2.	Pop into your mouth and enjoy!",
    category: "snack",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 7.3,
    carbohydrate: 1.3,
    calories: 150,
    fat: 12.7,
  },
  {  name: "Bones-to-Be Chicken Wingettes",
    instructions: "Use the Atkins recipe to make All Purpose Low-Carb Baking Mix for this recipe.  You will need half of a 1/3 cup (about 3 Tbsp) = half of a serving.
	1.	Heat oven to 450°F. Line a jelly-roll pan with foil, and spray with nonstick cooking spray.
	2.	Combine chili powder, 2 Tbsp baking mix, cayenne, mustard and salt in a large resealable bag. Add half of the wingettes, and shake to coat. Transfer to pan, and repeat with remaining wingettes.
	3.	Bake, turning occasionally, until crisp, browned and cooked through, 30 to 35 minutes. Transfer to a platter, and serve.",
    category: "snack",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 22.4,
    carbohydrate: 3.4,
    calories: 276,
    fat: 18.5,
  },
  {  name: "Caprese Salad",
    instructions: "	1.	Slice tomatoes and mozzarella.
	2.	Drizzle with olive oil.
	3.	Julienne the fresh chopped basil leaves and sprinkle on top.  Serve immediately.",
    category: "snack",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 10.1,
    carbohydrate: 2.3,
    calories: 294,
    fat: 27.4,
  },
  {  name: "Chocolate Peanut Butter Smoothie",
    instructions: "	For this recipe unsweetened coconut, almond or soy milk may be used.  Combine the ice, milk of choice, peanut butter, protein powder, cocoa powder, cocoa powder, stevia and salt (to taste) in a blender.  Blend until smooth.",
    category: "snack",
    vegan: false,
    paleo: false,
    basic:false,
    atkins: true,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 10.1,
    carbohydrate: 2.3,
    calories: 294,
    fat: 27.4,
  },
  {  name: "Overnight Oatmeal",
    instructions: "Combine water, oats, dried cranberries, dried apricots and salt in a 5- or 6-quart slow cooker. Turn heat to low. Put the lid on and cook until the oats are tender and the porridge is creamy, 7 to 8 hours.Stovetop VariationHalve the above recipe to accommodate the size of most double boilers: Combine 4 cups water, 1 cup steel-cut oats, 3 tablespoons dried cranberries, 3 tablespoons dried apricots and ⅛ teaspoon salt in the top of a double boiler. Cover and cook over boiling water for about 1½ hours, checking the water level in the bottom of the double boiler from time to time.",
    category: "breakfast",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 6,
    carbohydrate: 34,
    calories: 188,
    fat: 3,
  },
  {  name: "Thermos-Ready Smoothie",
    instructions: "Combine berries, banana, apple juice and tofu in a blender; blend until smooth.",
    category: "breakfast",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 6,
    carbohydrate: 62,
    calories: 276,
    fat: 3,
  },
  {  name: "Potato, Asparagus & Mushroom Hash",
    instructions: "Place a steamer basket in a large saucepan, add 1 inch of water and bring to a boil. Put potatoes in the basket and steam until barely tender when pierced with a skewer, 12 to 15 minutes, depending on size. When cool enough to handle, chop into ½-inch pieces.Heat 1 tablespoon oil in a large (not nonstick) skillet over medium heat. Add asparagus, mushrooms, shallot and garlic and cook, stirring often, until beginning to brown, 5 to 7 minutes. Remove to a plate.Add the remaining 2 tablespoons oil to the pan. Add onion and the potatoes and cook, stirring occasionally and scraping up the browned bits with a metal spatula, until the potatoes are browned, 4 to 8 minutes. Return the asparagus mixture to the pan along with roasted red pepper, sage, salt and pepper; cook, stirring, until heated through, about 1 minute more. Serve sprinkled with chives, if desired.
		Make Ahead Tip: Steam potatoes (Step 1); refrigerate for up to 2 days.",
    category: "breakfast",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 6,
    carbohydrate: 29,
    calories: 239,
    fat: 11,
  },
  {  name: "Slow-Cooker Chai Apple Butter",
    instructions: "Combine apples, brown sugar, vanilla, cardamom, cinnamon, coriander, turmeric and salt in a 6-quart or larger slow cooker. Cover and cook, stirring once or twice, for 5 hours on High. Set the lid ajar and continue cooking, stirring occasionally, until the apples are almost broken down, about 2 hours more. If desired, puree in a food processor until smooth.
		For easy cleanup, try a slow-cooker liner. These heat-resistant, disposable liners fit neatly inside the insert and help prevent food from sticking to the bottom and sides of your slow cooker.",
    category: "breakfast",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 6,
    carbohydrate: 29,
    calories: 239,
    fat: 11,
  },
  {  name: "Cinnamon Oranges",
    instructions: "With a sharp knife, remove rind and white pith from oranges. Cut each into 5 or 6 slices and arrange on 4 plates. Whisk together orange juice and lemon juice, sugar and cinnamon. Spoon over the orange slices.",
    category: "breakfast",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 6,
    carbohydrate: 22,
    calories: 86,
    fat: 0,
  },
  {  name: "Sweet Potato-Peanut Bisque",
    instructions: "Prick sweet potatoes in several places with a fork. Microwave on High until just cooked through, 7 to 10 minutes. Set aside to cool.Meanwhile, heat oil in a large saucepan or Dutch oven over medium-high heat. Add onion and cook, stirring, until it just begins to brown, 2 to 4 minutes. Add garlic and cook, stirring, for 1 minute more. Stir in juice, green chiles, ginger and allspice. Adjust the heat so the mixture boils gently; cook for 10 minutes.Meanwhile, peel the sweet potatoes and chop into bite-size pieces. Add half to the pot. Place the other half in a food processor or blender along with broth and peanut butter. Puree until completely smooth. Add the puree to the pot and stir well to combine. Thin the bisque with water, if desired. Season with pepper. Heat until hot. Garnish with cilantro, if desired.
		Make Ahead Tip: Cover and refrigerate for up to 3 days. Thin with water before reheating, if desired.",
    category: "lunch",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 8,
    carbohydrate: 29,
    calories: 286,
    fat: 16,
  },
  {  name: "Black Bean Croquettes with Fresh Salsa",
    instructions: "Preheat oven to 425°F. Coat a baking sheet with cooking spray.Mash black beans and cumin with a fork in a large bowl until no whole beans remain. Stir in corn and ¼ cup breadcrumbs. Combine tomatoes, scallions, cilantro, ½ teaspoon chili powder and salt in a medium bowl. Stir 1 cup of the tomato mixture into the black bean mixture.Mix the remaining ⅓ cup breadcrumbs, oil and the remaining ½ teaspoon chili powder in a small bowl until the breadcrumbs are coated with oil. Divide the bean mixture into 8 scant ½-cup balls. Lightly press each bean ball into the breadcrumb mixture, turning to coat. Place on the prepared baking sheet.Bake the croquettes until heated through and the breadcrumbs are golden brown, about 20 minutes. Stir avocado into the remaining tomato mixture. Serve the salsa with the croquettes.
		Easy cleanup: Recipes that require cooking spray can leave behind a sticky residue that can be hard to clean. To save time and keep your baking sheet looking fresh, line it with a layer of foil before you apply the cooking spray.",
    category: "lunch",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 16,
    carbohydrate: 61,
    calories: 404,
    fat: 13,
  },
  {  name: "Zesty Wheat Berry-Black Bean Chili",
    instructions: "Heat oil in a Dutch oven over medium-high heat. Add onion, bell pepper, garlic, chili powder, cumin, oregano, salt and pepper, and cook, stirring occasionally, until tender, about 5 minutes. Add beans, tomatoes, chipotle to taste, broth and brown sugar. Bring to a boil over high heat, reduce heat, cover, and simmer for 25 minutes.Stir in cooked wheat berries and heat through, about 5 minutes more. (If using frozen wheat berries, cook until thoroughly heated.) Remove from the heat. Stir in lime juice. Garnish each bowl with avocado and cilantro.
		Tips: Canned chipotle peppers (smoked jalapeños) in adobo sauce add heat and a smoky flavor. Look for the small cans with other Mexican foods in large supermarkets. Once opened, store in an airtight container for up to 2 weeks in the refrigerator or 6 months in the freezer.
		Wheat berries can be found in natural-foods markets and online at King Arthur Flour, (800) 827-6836, bakerscatalogue.com, and Bob's Red Mill",
    category: "lunch",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 16,
    carbohydrate: 58,
    calories: 371,
    fat: 11,
  },
  {  name: "Sesame Noodles",
    instructions: "Bring a large pot of water to a boil. Cook spaghetti until just tender, 9 to 11 minutes or according to package directions. Drain; rinse under cold water.Meanwhile, whisk soy sauce, sesame oil, canola oil, vinegar (or lime juice), crushed red pepper, ¼ cup scallions and 2 tablespoons cilantro (if using). Add noodles, snow peas and bell pepper; toss to coat.To serve, mix in sesame seeds and garnish with the remaining scallions and cilantro.
		Make Ahead Tip: Prepare through Step 2, up to 2 hours in advance.",
    category: "lunch",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 18,
    carbohydrate: 58,
    calories: 372,
    fat: 11,
  },
  {  name: "Indian-Spiced Eggplant & Cauliflower Stew",
    instructions: "Heat a Dutch oven over medium heat. Add curry powder, garam masala and mustard seeds and toast, stirring, until the spices begin to darken, about 1 minute. Transfer to a small bowl.Add oil, onion, garlic, ginger and salt to the pot and cook, stirring, until softened, 3 to 4 minutes. Stir in eggplant, cauliflower, tomatoes, chickpeas, water and the reserved spices. Bring to a simmer. Cover, reduce heat and cook, stirring occasionally, until the vegetables are tender, 15 to 20 minutes. Top each serving with a dollop of yogurt, if desired.
		Note: Hot Madras curry powder, located in the spice aisle of most supermarkets, adds a pleasant level of heat. Substitute regular curry powder for a milder flavor.
		Tip: Garam masala is a flavorful, fragrant blend of dry-roasted ground spices. It's in the spice section of most supermarkets and specialty stores.",
    category: "lunch",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 19,
    carbohydrate: 68,
    calories: 471,
    fat: 15,
  },
  {  name: "Kung Pao Tofu",
    instructions: "Pat tofu dry and cut into ½-inch cubes. Combine with ¼ teaspoon five-spice powder in a medium bowl.Heat canola oil in a large nonstick skillet over medium-high heat. Add tofu and cook, stirring every 1 to 2 minutes, until golden brown, 7 to 9 minutes total. Transfer to a plate.Meanwhile, whisk water, oyster sauce, cornstarch and the remaining ¼ teaspoon five-spice powder in a small bowl.Add broccoli, yellow and red bell pepper to the pan and cook, stirring occasionally, until beginning to soften, about 4 minutes. Add ginger and garlic and cook, stirring, until fragrant, about 30 seconds. Reduce heat to low, add the oyster sauce mixture and cook, stirring, until thickened, about 30 seconds. Return the tofu to the pan along with peanuts and stir to coat with sauce; stir in hot sesame oil (if using).
		Shopping tips: Five-spice powder is a blend of cinnamon, cloves, fennel seed, star anise and Szechuan peppercorns. Look for it in the spice section or with other Asian ingredients.
		Be sure to use “oyster-flavored” sauce (it's oyster-free) to make this vegetarian; both it and oyster sauce are found in the Asian-food section or at Asian markets.
		Ingredient note: Most supermarkets sell broccoli crowns, which are the tops of the bunches, with the stalks cut off. Although crowns are more expensive than entire bunches, they are convenient and there is considerably less waste.",
    category: "dinner",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 12,
    carbohydrate: 16,
    calories: 200,
    fat: 11,
  },
  {  name: "Sweet Potato & Black Bean Chili",
    instructions: "Heat oil in a Dutch oven over medium-high heat. Add sweet potato and onion and cook, stirring often, until the onion is beginning to soften, about 4 minutes. Add garlic, chili powder, cumin, chipotle and salt and cook, stirring constantly, for 30 seconds. Add water and bring to a simmer. Cover, reduce heat to maintain a gentle simmer and cook until the sweet potato is tender, 10 to 12 minutes.Add beans, tomatoes and lime juice; increase heat to high and return to a simmer, stirring often. Reduce heat and simmer until slightly reduced, about 5 minutes. Remove from heat and stir in cilantro.
		Make Ahead Tip: Cover and refrigerate for up to 3 days or freeze for up to 3 months.
		Note: Chipotle peppers are dried, smoked jalapeño peppers. Ground chipotle chile pepper can be found in the spice section of most supermarkets or online at penzeys.com.",
    category: "dinner",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 13,
    carbohydrate: 55,
    calories: 323,
    fat: 8,
  },
  {  name: "Szechuan Tofu & Green Bean Stir-Fry",
    instructions: "Whisk ¼ cup water, soy sauce, tomato paste, vinegar, sugar, crushed red pepper to taste and 1 teaspoon cornstarch in a small bowl. Set aside. Cut tofu into ½- to ¾-inch cubes and pat dry. Toss the tofu in a bowl with the remaining 2 tablespoons cornstarch to coat.Heat 1 tablespoon oil in a wok or large skillet over medium-high heat. Add the tofu and spread out across the surface of the pan. Let cook undisturbed for 2 minutes. Gently turn and stir. Continue cooking, stirring occasionally, until lightly browned and crispy, 2 to 3 minutes more. Transfer to a plate.Reduce heat to medium. Add the remaining 1 tablespoon oil to the pan. Add green beans, garlic and ginger; cook, stirring constantly, for 1 minute. Add the remaining ¼ cup water, cover and cook until the beans are crisp-tender, 2 to 4 minutes. Stir the reserved soy sauce mixture and pour it over the green beans. Cook, stirring, until thickened, about 1 minute. Add the tofu and cook, stirring, until heated through, about 1 minute more. Ingredient note: Chinkiang is a dark, slightly sweet vinegar. It is available in many Asian specialty markets. If unavailable, balsamic vinegar is an acceptable substitute.",
    category: "dinner",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 12,
    carbohydrate: 21,
    calories: 216,
    fat: 12,
  },
  {  name: "Indian Mango Dal",
    instructions: "Place lentils in a colander and rinse until the water runs clear. Combine lentils, 4 cups water, ½ teaspoon salt and turmeric in a large saucepan. Bring to a boil. Reduce heat to a simmer, partially cover and cook, stirring occasionally, for 15 minutes.Meanwhile, heat oil in a large nonstick skillet over medium heat. Add cumin seeds and cook until fragrant and starting to brown, about 30 seconds. Add onion; cook, stirring, until soft and beginning to brown, 4 to 6 minutes. Add garlic, ginger, coriander, cayenne and the remaining ½ teaspoon salt and cook, stirring, for 1 minute more.Stir the garlic mixture and mangoes into the lentils. Return to a simmer; cook, stirring occasionally, until the lentils are falling apart, 10 to 15 minutes more. Stir in cilantro.",
    category: "dinner",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 10,
    carbohydrate: 38,
    calories: 205,
    fat: 3,
  },
  {  name: "Oven-Roasted Squash with Garlic & Parsley",
    instructions: "Preheat oven to 375°F.Toss squash with 4 teaspoons oil, salt and ¼ teaspoon pepper. Spread evenly on a large baking sheet. Roast, stirring occasionally, until tender throughout and lightly browned, 30 to 45 minutes (depending on the variety of squash).Heat the remaining 2 teaspoons oil in a small skillet over medium heat. Add garlic and cook, stirring, until fragrant but not brown, 30 seconds to 1 minute. Toss the roasted squash with the garlic and parsley. Taste, adjust the seasoning and serve.
		Make Ahead Tip: Cut squash up to 1 day ahead; store airtight in the refrigerator.
		Kitchen Tip: Make it easier to cut a pumpkin, acorn squash or other winter squash: pierce in several places with a fork; microwave on High for 45 to 60 seconds. Use a large sharp knife to cut in half. Remove the seeds and stringy fibers with a spoon.
		Cut Down on Dishes: A rimmed baking sheet is great for everything from roasting to catching accidental drips and spills. For effortless cleanup and to keep your baking sheets in tip-top shape, line them with a layer of foil before each use.",
    category: "dinner",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 2,
    carbohydrate: 20,
    calories: 103,
    fat: 3,
  },
  {  name: "Kale Chips",
    instructions: "Position racks in upper third and center of oven; preheat to 400°F.If kale is wet, very thoroughly pat dry with a clean kitchen towel; transfer to a large bowl. Drizzle the kale with oil and sprinkle with salt. Using your hands, massage the oil and salt onto the kale leaves to evenly coat. Fill 2 large rimmed baking sheets with a layer of kale, making sure the leaves don't overlap. (If the kale won't all fit, make the chips in batches.)Bake until most leaves are crisp, switching the pans back to front and top to bottom halfway through, 8 to 12 minutes total. (If baking a batch on just one sheet, start checking after 8 minutes to prevent burning.)
		Make Ahead Tip: Store in an airtight container at room temperature for up to 2 days.
		Note: Choose organic kale when possible. Nonorganic can have high pesticide residue.
		Cut Down on Dishes: A rimmed baking sheet is great for everything from roasting to catching accidental drips and spills. For effortless cleanup and to keep your baking sheets in tip-top shape, line them with a layer of foil before each use.",
    category: "snack",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 5,
    carbohydrate: 16,
    calories: 110,
    fat: 5,
  },
  {  name: "Spiced Chickpea 'Nuts'",
    instructions: "Position rack in upper third of oven; preheat to 450°F.Blot chickpeas dry and toss in a bowl with oil, cumin, marjoram, allspice and salt. Spread on a rimmed baking sheet. Bake, stirring once or twice, until browned and crunchy, 25 to 30 minutes. Let cool on the baking sheet for 15 minutes.
		Make Ahead Tip: Cover and store at room temperature for up to 2 days.",
    category: "snack",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 4,
    carbohydrate: 19,
    calories: 131,
    fat: 5,
  },
  {  name: "Pureed Broccoli Soup",
    instructions: "Heat butter and oil in a Dutch oven over medium heat until the butter melts. Add onion and celery; cook, stirring occasionally, until softened, 4 to 6 minutes. Add garlic and thyme (or parsley); cook, stirring, until fragrant, about 10 seconds.Stir in broccoli. Add water and broth; bring to a lively simmer over high heat. Reduce heat to maintain a lively simmer and cook until very tender, about 8 minutes.Puree the soup in batches in a blender until smooth. (Use caution when pureeing hot liquids.) Stir in half-and-half (if using), salt and pepper.
		Make Ahead Tip: Cover and refrigerate for up to 4 days or freeze for up to 3 months",
    category: "snack",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 9,
    carbohydrate: 17,
    calories: 160,
    fat: 8,
  },
  {  name: "Garlic & Herb Pita Chips",
    instructions: "Position oven racks in middle and lower third of oven; preheat to 350°F. Coat 2 large baking sheets with nonstick cooking spray.Cut pitas into 8 wedges each and separate each wedge at the fold. Place the pita wedges, rough-side up, in an even layer on the prepared baking sheets. Brush with oil and sprinkle with Italian seasoning, garlic powder and salt.Bake the pita wedges, switching the baking sheets halfway through, until golden and crispy, 6 to 10 minutes (depending on the thickness).
		Make Ahead Tip: Store in an airtight container for up to 4 days.",
    category: "snack",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 3,
    carbohydrate: 18,
    calories: 117,
    fat: 4,
  },
  {  name: "Chile-Lime Peanuts",
    instructions: "Position racks in the upper and lower thirds of oven; preheat to 250°F.Whisk lime juice, chili powder, salt and cayenne in a large bowl. Add peanuts; toss to coat. Divide between 2 large rimmed baking sheets; spread in an even layer.Bake, stirring every 15 minutes, until dry, about 45 minutes. Let cool completely. Store in an airtight container.
		Make Ahead Tip: Store in an airtight container for up to 3 weeks.",
    category: "snack",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 5,
    carbohydrate: 5,
    calories: 111,
    fat: 9,
  },
  {  name: "Edamame-Ginger Dip",
    instructions: "Cook edamame according to package directions.Puree the cooked edamame, water, soy sauce, ginger, vinegar, tahini, garlic, salt and hot sauce in a food processor until smooth. Chill for 1 hour before serving.
		Make Ahead Tip: Cover and refrigerate for up to 5 days.",
    category: "snack",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 5,
    carbohydrate: 14,
    calories: 108,
    fat: 3,
  },
  {  name: "Microwave Potato Chips",
    instructions: "Slice potatoes into thin ( ⅛-inch) rounds. Toss the slices in a medium bowl with oil and salt to coat evenly.Coat a large microwave-proof plate with cooking spray. Arrange some potato slices in a single layer on the plate. Microwave, uncovered, on High until some slices start to brown, 2 to 3 minutes (depending on potato thickness and microwave power). Turn the slices over and continue microwaving until they start to crisp and brown around the edges, 2 to 4 minutes more. Check frequently and rearrange slices as needed to prevent scorching. Transfer the chips to another plate and allow to cool completely. (They will crisp more as they cool.) Repeat with the remaining potato slices.",
    category: "snack",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 3,
    carbohydrate: 26,
    calories: 141,
    fat: 2,
  },
  {  name: "Garlic & White Bean Dip",
    instructions: "To prepare poached garlic & garlic oil: Bring water to a boil in a medium saucepan. Remove from the heat, add garlic cloves and stir to submerge. Let stand until the garlic skins are softened and cool enough to handle, about 50 minutes. Strain the garlic, remove the skins and cut off the hard nub where the clove was attached to the head.Place the garlic, canola oil and olive oil in a medium saucepan; bring to a gentle simmer over medium-low heat. Reduce the heat to low and maintain a very gentle simmer (it may be necessary to slide the pan to the edge of the burner). Simmer until the cloves are golden and very soft when pressed with a fork, 40 to 50 minutes. Let cool for 30 minutes.Transfer the cooled garlic to a sieve to drain, reserving the oil. Transfer the garlic to a food processor and puree until smooth, scraping down the sides occasionally. (If it makes more than ½ cup, store the extra in the refrigerator for up to 1 week.)To prepare bean dip: Combine ½ cup of the reserved garlic oil, onion and salt in a large skillet. Cook over medium heat until the onion is softened but not browned, 6 to 9 minutes. Stir in beans and cook until heated through, about 2 minutes. Transfer to the food processor, add lemon juice and puree with ½ cup garlic puree until smooth. Serve warm or cold. (Store extra garlic oil in the refrigerator for up to 1 week.) Make Ahead Tip: To make ahead: Cover and refrigerate garlic puree for up to 1 week or freeze for up to 6 months; refrigerate oil for no more than 1 week. Cover and refrigerate the dip for up to 3 days.",
    category: "snack",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 2,
    carbohydrate: 6,
    calories: 96,
    fat: 8,
  },
  {  name: "Roasted Garlic Hummus",
    instructions: "Preheat oven to 425°F. Remove the loose papery outside skin from the garlic head without separating the cloves. Slice off the top ½ inch. Wrap in a small square of foil and roast until the garlic is very soft, about 40 minutes. Unwrap and cool slightly. Separate the cloves and peel.Puree the garlic, chickpeas, lemon juice, soy sauce, tahini and water in a food processor. Add more or less water as necessary to make a fairly firm dip.Transfer to a small serving bowl, stir in parsley and season with salt. Garnish with a sprig of parsley and a sprinkling of paprika.",
    category: "snack",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 2,
    carbohydrate: 8,
    calories: 47,
    fat: 1,
  },
  {  name: "Spinach with Chickpeas",
    instructions: "Rinse spinach and let drain in a colander. With water still clinging to it, place half the spinach in a Dutch oven over medium heat. Cook, tossing with tongs and adding the remaining spinach by the handful until all is added and wilted, 6 to 8 minutes. Drain in the colander. Let cool slightly, then coarsely chop.Carefully wipe out the pan, then heat 1 tablespoon oil over medium heat. Add onion and garlic and cook, stirring, until the onion is tender and lightly browned, 8 to 10 minutes. Stir in chickpeas, thyme, oregano, cumin, salt and paprika. Using a potato masher, mash some of the chickpeas, then cook, stirring, for 3 minutes. Stir in raisins and broth, scraping up any browned bits. Add the chopped spinach and stir gently to combine. Remove from the heat and let stand 10 minutes. Drizzle with the remaining 2 tablespoons oil just before serving.",
    category: "snack",
    vegan: true,
    paleo: false,
    basic:false,
    atkins: false,
    ectomorphs: true,
    mesomorphs: true,
    endomorphs: true,
    protein: 4,
    carbohydrate: 17,
    calories: 115,
    fat: 4,
  }
]

RECIPES.each do |recipe|
  Recipe.find_or_create_by!(
    name: recipe[:name],
    instructions: recipe[:instructions],
    category: recipe[:category],
    vegan: recipe[:vegan],
    paleo: recipe[:paleo],
    basic: recipe[:basic],
    atkins: recipe[:atkins],
    ectomorphs: recipe[:ectomorphs],
    mesomorphs: recipe[:mesomorphs],
    endomorphs: recipe[:endomorphs],
    protein: recipe[:protein],
    carbohydrate: recipe[:carbohydrate],
    calories: recipe[:calories],
    fat: recipe[:fat]
  )
end
